# Generated by Django 5.0.2 on 2024-03-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, unique=True, verbose_name="title")),
                ("slug", models.SlugField(blank=True, max_length=150)),
                (
                    "files",
                    models.ManyToManyField(
                        related_name="tags", related_query_name="tag", to="files.file", verbose_name="files"
                    ),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
            },
        ),
    ]
