# Generated by Django 5.0.2 on 2024-03-16 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_file_preview"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("latitude", models.FloatField(verbose_name="latitude")),
                ("longitude", models.FloatField(verbose_name="longitude")),
                ("country", models.CharField(blank=True, max_length=100, null=True, verbose_name="country")),
                ("city", models.CharField(blank=True, max_length=100, null=True, verbose_name="city")),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geodata",
                        related_query_name="geodata",
                        to="files.file",
                        verbose_name="file",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Geodata",
                "verbose_name_plural": "Files Geodata",
            },
        ),
    ]
