# Generated by Django 5.0.2 on 2024-02-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.URLField(max_length=250, null=True, verbose_name="avatar"),
        ),
    ]
