# Generated by Django 5.0.2 on 2024-03-12 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("albums", "0002_remove_album_members_albummembership"),
        ("albums", "0003_album_members_alter_albummembership_album_and_more"),
        ("albums", "0004_alter_albummembership_options_and_more"),
    ]

    dependencies = [
        ("albums", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="members",
        ),
        migrations.CreateModel(
            name="AlbumMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_redactor", models.BooleanField(default=False)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="albums.album", verbose_name="album"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="member"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="album",
            name="members",
            field=models.ManyToManyField(
                related_name="albums",
                related_query_name="album",
                through="albums.AlbumMembership",
                to=settings.AUTH_USER_MODEL,
                verbose_name="members",
            ),
        ),
        migrations.AlterField(
            model_name="albummembership",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                related_query_name="membership",
                to="albums.album",
                verbose_name="album",
            ),
        ),
        migrations.AlterField(
            model_name="albummembership",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                related_query_name="membership",
                to=settings.AUTH_USER_MODEL,
                verbose_name="member",
            ),
        ),
        migrations.AlterModelOptions(
            name="albummembership",
            options={"verbose_name": "album membership", "verbose_name_plural": "album memberships"},
        ),
        migrations.AlterModelTable(
            name="albummembership",
            table="albums_membership",
        ),
    ]
