# Generated by Django 5.0.2 on 2024-03-07 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0002_remove_album_members_albummembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="members",
            field=models.ManyToManyField(
                related_name="albums",
                related_query_name="album",
                through="albums.AlbumMembership",
                to=settings.AUTH_USER_MODEL,
                verbose_name="members",
            ),
        ),
        migrations.AlterField(
            model_name="albummembership",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                related_query_name="membership",
                to="albums.album",
                verbose_name="album",
            ),
        ),
        migrations.AlterField(
            model_name="albummembership",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                related_query_name="membership",
                to=settings.AUTH_USER_MODEL,
                verbose_name="member",
            ),
        ),
    ]
