# Generated by Django 5.0.2 on 2024-03-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0003_album_members_alter_albummembership_album_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="albummembership",
            options={"verbose_name": "album membership", "verbose_name_plural": "album memberships"},
        ),
        migrations.AlterModelTable(
            name="albummembership",
            table="albums_membership",
        ),
    ]
